### ISSUE TITLE
The extension doesn't work with the latest version of Visual Code

### ISSUE THREAD

**Issue by RoyalBoogie** [usernamehw/vscode-remove-empty-lines#4] opened 2020-05-27 09:54 UTC
Hi, 

I've been using your extension for quite a while now. I've never encountered any problems and I find it very convenient. 
But this one doesn't work anymore. I tried to remove empty line in a php file and in a javascript file, nothing happened. 

I'm using the below version of VSCode, maybe a compatibility problem. 

Version : 1.45.1 (system setup)
Commit : 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date : 2020-05-14T08:27:35.169Z
Electron : 7.2.4
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Windows_NT x64 10.0.18362

I hope this will be fix soon.

**Comment by usernamehw** [comment] 2020-05-27 10:09
It's working in the latest version of Insiders and Stable on my system:
```
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

There are no changes in the last 6+ month to this extension, so it's unlikely that the problem is with it.

Are there any problems in the Devtools `Developer: Toggle Developer Tools` ?

Are you running it from Command Palette or from a keybinding? It might be a key conflict.

**Comment by RoyalBoogie** [comment] 2020-05-27 10:38
It seems that there are no errors related to the extension. 

![debugger](https://user-images.githubusercontent.com/15236581/83009282-ce5ac000-a016-11ea-9ce6-9cbfec8342f5.png)

I don't use a keybinding : 

![vscode](https://user-images.githubusercontent.com/15236581/83009293-d1ee4700-a016-11ea-8f89-5be3ee6892c8.png)

I tried to uninstall and install it again. I tried to reboot VSCode. Nothing is happening.

**Comment by RoyalBoogie** [comment] 2020-05-27 12:45
I notice that Emmet doesn't work too. So I tried to create a new folder with a new html file and a new javascript file. Emmet works fine and your extension too. So the problem is due to my other project but I don't know why. I tried with an other existing Javascript Project and it doesn't work too. 
Thank you for your answer and your time. I will try to find a solution.

**Comment by usernamehw** [comment] 2020-05-27 16:18
Maybe the problem is with some other extension that crashes/makes extension host unresponsive.

You can try to run `Developer: Show Running Extensions` to see which extension takes the most time to load or has errors.

BTW, I think this extension [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) should have improved performance in the second version: [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2) 

Closing this issue as unactionable.

**Closed as completed by usernamehw** 2020-05-27 16:18 UTC
